version: '2'

services:
  mysql_db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: 'main'
      MYSQL_USER: 'attentive'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  
  postgres_db:
    image: 'postgres:10.6'
    environment:
      POSTGRES_USER: 'attentive'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'main'
      POSTGRES_ROOT_PASSWORD: 'password'
    ports:
      - "54320:5432"